plugins {
    id 'base'
}

allprojects {
    repositories {
        mavenCentral()
    }
}

allprojects {
    plugins.withId('java') {
        java {
            toolchain {
                languageVersion.set(JavaLanguageVersion.of(17))
            }
        }
    }
}

subprojects {
    plugins.withId('java') {
        dependencies {
            testImplementation platform('org.junit:junit-bom:5.10.0')
            testImplementation 'org.junit.jupiter:junit-jupiter'

            implementation group: 'com.google.guava', name: 'guava', version: guava_version
            implementation group: 'com.google.code.gson', name: 'gson', version: gson_version

            implementation group: 'org.jetbrains', name: 'annotations', version: annotations_version

            implementation group: 'org.jspecify', name: 'jspecify', version: jspecify_version
        }

        test {
            useJUnitPlatform()
        }
    }
}

tasks.named('build') {
    dependsOn(':codegen:build')
    dependsOn(':core:build')
}