package net.quepierts.animata4j.core.dsl.ast;

public enum NodeType {
    EXPR_ARRAY_ACCESS,
    EXPR_MEMBER_ACCESS,
    EXPR_ASSIGN,
    EXPR_CONSTRUCT,
    EXPR_INITIALIZER,
    EXPR_CALL,

    EXPR_IDENTIFIER,
    EXPR_LITERAL_BOOLEAN,
    EXPR_LITERAL_DECIMAL,
    EXPR_LITERAL_INTEGER,
    EXPR_LITERAL_STRING,

    EXPR_BINARY,
    EXPR_TERNARY,
    EXPR_UNARY,

    EXPR_EMPTY,

    STMT_BLOCK,
    STMT_EXPRESSION,
    STMT_IF,
    STMT_RETURN,
    STMT_VARIABLE_DECL,
    STMT_FOR,
    STMT_WHILE,
    STMT_SWITCH,
    STMT_CASE,
    STMT_CONTINUE,
    STMT_BREAK,
    STMT_EMPTY,

    DECL_FUNCTION,
    DECL_PARAMETER,
    DECL_STRUCT,
    DECL_MEMBER,
    DECL_VARIABLE,
    DECL_BLOCK,     // in, out, uniform

    TYPE_PRIMITIVE,
    TYPE_STRUCT,
    TYPE_VOID,
    TYPE_ARRAY,

    DEF_FUNCTION,

    COMPILATION_UNIT,
    CUSTOM  // placeholder
}
