plugins {
    id 'java'
}

group = 'net.quepierts.animata4j.core'
version = '1.0-SNAPSHOT'

repositories {
    mavenCentral()
}

dependencies {
    testImplementation platform('org.junit:junit-bom:5.10.0')
    testImplementation 'org.junit.jupiter:junit-jupiter'

    implementation group: 'com.google.guava', name: 'guava', version: guava_version
    implementation group: 'com.google.code.gson', name: 'gson', version: gson_version

    implementation group: 'it.unimi.dsi', name: 'fastutil', version: fastutil_version
    implementation group: 'org.joml', name: 'joml', version: joml_version

    implementation group: 'org.jetbrains', name: 'annotations', version: annotations_version

    implementation group: 'org.slf4j', name: 'slf4j-api', version: slf4j_api_version
    implementation group: 'org.slf4j', name: 'slf4j-simple', version: slf4j_simple_version

    compileOnly group: 'org.projectlombok', name: 'lombok', version: lombok_version
    annotationProcessor group: 'org.projectlombok', name: 'lombok', version: lombok_version
}

test {
    useJUnitPlatform()
}