plugins {
    id 'java'
    id 'idea'
    id 'animata-codegen'

    id 'java-library'
    id 'maven-publish'
    id 'signing'

    id 'io.freefair.lombok' version '9.2.0'
}

def getGitCommitCount() {
    def stdout = new ByteArrayOutputStream()
    exec {
        commandLine 'git', 'rev-list', '--count', 'HEAD'
        standardOutput = stdout
    }
    return stdout.toString().trim().toInteger()
}

def buildNumber = getGitCommitCount()

group       = 'net.quepierts.animata4j'
version     = hasProperty("build.snapshot") ?
            "${project_version}-SNAPSHOT" :
            "${project_version}"

java {
    withJavadocJar()
    withSourcesJar()
}

apply from: "jar.gradle"
apply from: "publishing.gradle"

dependencies {
    implementation group: 'it.unimi.dsi', name: 'fastutil', version: fastutil_version
    implementation group: 'org.joml', name: 'joml', version: joml_version

    implementation group: 'org.slf4j', name: 'slf4j-api', version: slf4j_api_version
    implementation group: 'org.slf4j', name: 'slf4j-simple', version: slf4j_simple_version

    compileOnly project(':codegen-annotations')
}